import type { Chapter } from '../manual-types';

export const foundationChapters: Chapter[] = [
  {
    index: 0,
    slug: 'overview',
    navTitle: 'Master Architecture',
    eyebrow: 'FULL WORKFLOW',
    title: 'От BASE IMAGE до активного LQ output',
    lede:
      'Полный граф объединяет SDXL, ControlNet, несколько систем масок, PEOPLE/PPL, основной FLUX img2img и сохранённые post-processing ветки. Эта страница задаёт карту, относительно которой читаются все остальные главы.',
    status: 'confirmed',
    statusNote: '252 nodes · 341 links · 16 formal groups · 28 controls в derived specification',
    visual: 'master',
    category: 'foundation',
    stage: 'architecture',
    relatedNodes: [79, 783, 1, 14, 565, 779, 459, 573, 67, 57, 53, 730, 833, 848, 849],
    relatedChapters: ['inputs', 'control-panel', 'sdxl', 'main-flux', 'output'],
    sections: [
      {
        id: 'production-path',
        eyebrow: '01 · ACTIVE DATA PLANE',
        title: 'Текущий доказуемый production path заканчивается на node 730',
        paragraphs: [
          'BASE IMAGE 79 проходит через общий resize 783. Далее SDXL использует checkpoint 2, conditioning 5/6, ControlNet stack 417→419→418, latent selector 535, KSampler 1 и decode 14.',
          'После первого detail transfer 565 и центрального fan-out 779 изображение соединяется с PEOPLE/PPL. Выбранный результат 459 проходит detail transfer 573, VAE Encode 67, основной FLUX sampler 57, decode 53 и активный LQ save 730.',
        ],
        table: {
          columns: ['Stage', 'Nodes', 'Current role', 'State'],
          rows: [
            ['Input / resize', '79 → 783', 'BASE IMAGE и общий canvas', 'ACTIVE'],
            ['Main SDXL', '2 / 5 / 6 / 418 / 535 / 1 / 14', 'Создание или преобразование базовой сцены', 'ACTIVE'],
            ['Detail bridge', '565 → 779', 'Сохранение архитектурных деталей и fan-out', 'ACTIVE'],
            ['PEOPLE / PPL', '408…459', 'Генерация, mask, preparation, composite, selection', 'ACTIVE · MODE 1'],
            ['Main FLUX', '573 → 67 → 57 → 53', 'Финальный img2img refinement', 'ACTIVE'],
            ['Current save', '53 → 730', 'LQ1 JPG output', 'ACTIVE'],
          ],
        },
      },
      {
        id: 'optional-tail',
        eyebrow: '02 · SAVED BUT BYPASSED',
        title: 'Upscale и Add Logo существуют в графе, но не выполняются текущим профилем',
        paragraphs: [
          'В спецификации 227 nodes имеют mode 0, а 25 nodes — mode 4. Эти 25 nodes составляют processing групп Process UPSCALE и Process ADD LOGO.',
          'Save nodes 531 и 293 сами имеют mode 0, однако их upstream 833/848/849 находится в mode 4. Поэтому корректная формулировка — upstream-bypassed, а не save-node-bypassed.',
        ],
        facts: [
          { status: 'confirmed', title: 'HQ branch', text: '53 → 834 → 833 → 531 сохранён в topology; 834/833 имеют mode 4.' },
          { status: 'confirmed', title: 'Overlay branch', text: '833 → 848 → 849 → 15/293 сохранён; processing nodes 840–851 имеют mode 4.' },
          { status: 'not-confirmed', title: 'Runtime pixels', text: 'Workflow JSON не доказывает, что HQ, logo overlay или final preview когда-либо выполнялись в этой конфигурации.' },
        ],
      },
      {
        id: 'current-profile',
        eyebrow: '03 · CURRENT PROFILE',
        title: 'Сохранённые modes определяют фактический маршрут',
        table: {
          columns: ['Control / node', 'Stored value', 'Effective meaning'],
          rows: [
            ['541', '1', 'TXT+CNET2IMG; empty latent 3; denoise 1.0'],
            ['168 / 721', '1 / 0', 'Plain SDXL; IPAdapter selected away и weight 0'],
            ['453', '1', 'GLOBAL FLUX conditioning 811'],
            ['543', '1', 'FLUX PEOPLE source для связанных selectors'],
            ['565 / 573 / 720', 'add / 0.09', 'Два активных detail-transfer stages'],
            ['834 / 833 / 848 / 849', 'mode 4', 'Post-FLUX upscale и overlays bypassed'],
          ],
        },
      },
      {
        id: 'evidence-limit',
        eyebrow: '04 · SOURCE LIMIT',
        title: 'Topology подтверждена производной спецификацией, но raw workflow не приложен',
        facts: [
          { status: 'confirmed', title: 'Derived source', text: 'HANSEN_WORKFLOW_SPEC.json содержит nodes, links, groups, controls и SHA исходного workflow.' },
          { status: 'not-confirmed', title: 'Independent hash check', text: 'Epspoziciya_archviz_ph_sdxlflux_v001.json отсутствует в опубликованном ZIP, поэтому SHA нельзя пересчитать в этом checkout.' },
          { status: 'not-confirmed', title: 'Visual result', text: 'Связный маршрут не доказывает качество, скорость или наличие людей в конкретном render.' },
        ],
      },
    ],
  },
  {
    index: 0,
    slug: 'graph-reading',
    navTitle: 'How to Read the Graph',
    eyebrow: 'GRAPH LANGUAGE',
    title: 'Data plane, control plane и фактический runtime value',
    lede:
      'Чтобы читать Hansen graph без ошибок, нужно разделять тип сигнала, сохранённое значение widget, linked input, selector state и bypass mode.',
    status: 'confirmed',
    statusNote: 'Типы links, slots и node modes извлечены из HANSEN_WORKFLOW_SPEC.json',
    visual: 'graph-reading',
    category: 'foundation',
    stage: 'architecture',
    relatedNodes: [543, 715, 552, 535, 542, 592, 600, 630, 685, 695, 732],
    relatedChapters: ['control-panel', 'selector-logic', 'node-index'],
    sections: [
      {
        id: 'signal-types',
        eyebrow: '01 · SIGNAL TYPES',
        title: 'Link type показывает, что передаётся между nodes',
        table: {
          columns: ['Type', 'Links', 'Практический смысл'],
          rows: [
            ['IMAGE', '126', 'Pixels / image batch'],
            ['INT', '55', 'Mode, size, steps и linked selector value'],
            ['STRING', '26', 'Prompt fragments и text routing'],
            ['MASK', '23', 'Область действия composite / inpaint / detail transfer'],
            ['CONDITIONING', '15', 'Закодированное prompt conditioning'],
            ['MODEL', '13', 'Model object после loader или patch'],
            ['FLOAT', '11', 'Strength / denoise / weight'],
            ['LATENT', '10', 'Latent image до decode'],
          ],
        },
      },
      {
        id: 'widget-vs-link',
        eyebrow: '02 · PRECEDENCE',
        title: 'Linked input важнее текста, видимого внутри selector',
        paragraphs: [
          'Node 715 хранит widget value 2, но его Input socket связан с node 543, где текущий value равен 1. Поэтому effective selection равен input 1.',
          'Та же модель применяется к 459, 522, 535, 542, 552, 592, 630, 685, 695 и 732. При диагностике сначала проверяй связь control, затем widget.',
        ],
        facts: [
          { status: 'confirmed', title: 'Node 715', text: '543 → Input of 715; stored 2 не является authoritative, пока control-link подключён.' },
          { status: 'inferred', title: 'Debug rule', text: 'Если UI label и реальный route расходятся, tracing нужно начинать от source control link.' },
        ],
      },
      {
        id: 'node-state',
        eyebrow: '03 · EXECUTION STATE',
        title: 'Active, selected away и bypassed — разные состояния',
        bullets: [
          'ACTIVE: node mode 0 и его input выбран текущим selector.',
          'SELECTED AWAY: node mode 0, но downstream selector берёт другой вход.',
          'BYPASSED: node mode 4; graph сохраняет node и links, но processing выключен.',
          'DIAGNOSTIC ONLY: preview/comparer получает данные, но не формирует финальный result.',
        ],
      },
    ],
  },
  {
    index: 0,
    slug: 'inputs',
    navTitle: 'Inputs & Data Contracts',
    eyebrow: 'INPUTS · RESIZE · BATCH',
    title: 'Какие файлы и размеры входят в workflow',
    lede:
      'BASE IMAGE обязателен; depth, references, RGB mask и overlays используются только соответствующими ветками. Между ними работают несколько resize и original/resized switches.',
    status: 'confirmed',
    statusNote: 'Filenames и consumers подтверждены serialized LoadImage nodes и topology',
    visual: 'inputs',
    category: 'foundation',
    stage: 'input',
    relatedNodes: [25, 41, 42, 79, 301, 309, 338, 693, 695, 685, 702, 780, 781, 782, 783, 784, 785, 827],
    relatedChapters: ['control-panel', 'controlnet', 'ipadapter-lora', 'positioning'],
    sections: [
      {
        id: 'input-files',
        eyebrow: '01 · FILE CONTRACTS',
        title: 'Семь LoadImage nodes обслуживают разные branches',
        table: {
          columns: ['Node', 'Stored filename', 'Role', 'Required when'],
          rows: [
            ['79', 'V_1_di.jpg', 'BASE IMAGE; image + optional mask', 'Всегда'],
            ['25', 'V_1_d.jpg', 'External depth source', '456 = 1 для Depth'],
            ['41', 'reference .jfif', 'Вторая IPAdapter reference', '168 = 2 и 630 = 2'],
            ['42', 'reference .jfif', 'Первая IPAdapter reference', '168 = 2'],
            ['338', 'V_1_g.jpg', 'RGB/CMY/B/W mask atlas', 'Если используются color-coded masks'],
            ['301', 'logo.png', 'Первый overlay/logo', 'После включения Add Logo'],
            ['309', 'overlay image', 'Второй overlay', 'После включения Add Logo'],
          ],
        },
      },
      {
        id: 'size-contracts',
        eyebrow: '02 · SIZE CONTRACTS',
        title: 'В графе одновременно существуют несколько canvas sizes',
        table: {
          columns: ['Stage', 'Node(s)', 'Stored / linked size', 'Cardinality'],
          rows: [
            ['Working base', '702 → 783', '1536 по длинной стороне / shared W,H', 'image batch from input'],
            ['External maps', '784 / 785', '1920 × 1920, resize, divisible by 64', 'image'],
            ['PEOPLE latent', '827', '1312 × 1920', 'batch 1'],
            ['PEOPLE detection canvas', '780', '1920 × 1920', 'image + mask'],
            ['SDXL latent', '3', 'W,H linked from 783', 'batch 4'],
            ['Main FLUX model sampling', '64', 'W,H linked from 783', 'shared canvas'],
          ],
        },
      },
      {
        id: 'original-resized',
        eyebrow: '03 · ROUTING',
        title: 'Node 693 выбирает original или resized canvas для двух downstream paths',
        paragraphs: [
          'Control 693 связан с selectors 695 и 685. Первый определяет source для общего image switch 592, второй — canvas для альтернативного PPL return 459.',
          'Любая диагностика positioning должна сверять размер image, mask и canvas на 780–785, а не только визуальный preview.',
        ],
        facts: [
          { status: 'confirmed', title: 'Current value', text: '693 = 1, то есть RESIZE INPUT.' },
          { status: 'not-confirmed', title: 'File availability', text: 'Serialized filename не доказывает наличие файла в активной ComfyUI input folder.' },
        ],
      },
    ],
  },
  {
    index: 0,
    slug: 'control-panel',
    navTitle: 'Controls & Mode Presets',
    eyebrow: 'CONTROL PLANE',
    title: '28 controls, которые меняют маршрут и параметры графа',
    lede:
      'Controls Hansen workflow связывают режим генерации, источники ControlNet, prompt routing, PEOPLE source, рабочее разрешение и shared sampler settings.',
    status: 'confirmed',
    statusNote: 'Полный control inventory извлечён из 16_ALL_CONTROLS_REFERENCE.csv и topology',
    visual: 'controls',
    category: 'foundation',
    stage: 'control',
    relatedNodes: [168, 453, 456, 459, 479, 522, 535, 541, 543, 552, 592, 600, 602, 607, 608, 609, 630, 685, 693, 695, 702, 715, 717, 720, 721, 722, 723, 771],
    relatedChapters: ['graph-reading', 'selector-logic', 'sdxl', 'controlnet', 'main-flux'],
    sections: [
      {
        id: 'all-controls',
        eyebrow: '01 · INVENTORY',
        title: 'Все user-facing и linked controls',
        table: {
          columns: ['Node', 'Current', 'Purpose / options', 'Downstream'],
          rows: [
            ['168', '1', '1 SDXL / 2 SDXL+IPA', '87'],
            ['453', '1', '1 GLOBAL / 2 Florence2 conditioning', '62, 833'],
            ['456', '1', '1 input maps / 2 preprocessors', '542, 732'],
            ['459', '1 linked', 'FLUX or alternative PEOPLE composite', '480, 573'],
            ['479', '—', 'Fast Groups Bypasser; saved group toggles absent', 'UI only'],
            ['522', '1 linked', 'FLUX or alternative mask source', '508'],
            ['535', '1 linked', 'Empty / VAE-encoded SDXL latent', '1'],
            ['541', '1', '1 TXT+CNET2IMG / 2 IMG+CNET2IMG', '535, 592, 602'],
            ['543', '1', '1 PPL FLUX / 2 INPUT', '459, 522, 552, 715'],
            ['552', '1 linked', 'PEOPLE source for resize/inpaint', '503, 518, 780'],
            ['592', '1 linked', 'Selected main image', '585, 580, 536, 775, 565'],
            ['600', 'computed', 'Mode-dependent denoise output', '1'],
            ['602', 'a != b', 'Generation-mode comparison', '600'],
            ['607', '1.0', 'TXT mode denoise', '600'],
            ['608', '0.3', 'IMG mode denoise', '600'],
            ['609', '1', 'Comparison constant', '602'],
            ['630', '1 linked', '1 first / 2 both IPA references', '9'],
            ['685', '1 linked', 'Resized/original alternative composite', '459'],
            ['693', '1', '1 RESIZE / 2 ORIGINAL', '695, 685'],
            ['695', '1 linked', 'Resized/original base', '592'],
            ['702', '1536', 'Working resize target', '783 W/H'],
            ['715', '2 stored · 1 effective', 'Return / Downstream Selector', '552'],
            ['717', '0.44', 'Color from environment strength', '477'],
            ['720', '0.09', 'Stage 1 & 2 detail-transfer strength', '565, 573'],
            ['721', '0', 'IPAdapter weight', '7'],
            ['722', '0.31', 'Canny ControlNet strength', '419'],
            ['723', '0.36', 'Depth ControlNet strength', '417'],
            ['771', '24', 'Shared FLUX/PPL/inpaint/upscale steps', '59, 498, 819, 833'],
          ],
        },
      },
      {
        id: 'current-preset',
        eyebrow: '02 · CURRENT SAVED PROFILE',
        title: 'Активный snapshot, а не универсальная рекомендация',
        bullets: [
          '541=1: TXT+CNET2IMG, empty latent, denoise 1.0.',
          '456=1: input1 sources для Depth/Canny switches.',
          '168=1 и 721=0: plain SDXL, IPAdapter не влияет.',
          '453=1: GLOBAL FLUX prompt.',
          '543=1: PPL FLUX source.',
          '693=1: resized input.',
          'Upscale/Add Logo processing: mode 4.',
        ],
      },
      {
        id: 'safe-switching',
        eyebrow: '03 · MODE RECIPE',
        title: 'Меняй source control, затем проверяй все связанные selectors',
        paragraphs: [
          'Для переключения режима сначала меняется master control, затем проверяются effective values downstream, затем первый preview выбранной ветки. Визуальные presets в учебнике не должны выглядеть как live управление ComfyUI.',
        ],
        facts: [
          { status: 'inferred', title: 'Safe order', text: 'Source files/models → master control → linked selectors → first preview → final downstream.' },
          { status: 'not-confirmed', title: 'Fast Groups Bypasser toggles', text: 'Node 479 не содержит сериализованных per-group widget values; точное UI-состояние восстанавливается только по node modes.' },
        ],
      },
    ],
  },
  {
    index: 0,
    slug: 'models-dependencies',
    navTitle: 'Models & Dependencies',
    eyebrow: 'LOADERS · CUSTOM NODES',
    title: 'Model manifest и package-to-node карта',
    lede:
      'Workflow хранит точные filenames loaders и provider IDs, но не доказывает наличие файлов, текущую установленную версию или runtime compatibility.',
    status: 'confirmed',
    statusNote: 'Filenames и provider IDs присутствуют в serialized nodes; runtime status не подтверждён',
    visual: 'models',
    category: 'foundation',
    stage: 'runtime',
    relatedNodes: [2, 12, 13, 21, 23, 54, 87, 107, 112, 153, 234, 466, 467],
    relatedChapters: ['resources', 'sdxl', 'controlnet', 'ipadapter-lora', 'main-flux'],
    sections: [
      {
        id: 'model-manifest',
        eyebrow: '01 · MODEL FILES',
        title: 'Загрузчики и их consumers',
        table: {
          columns: ['Loader', 'Filename / repo', 'Stage', 'Current use'],
          rows: [
            ['2', 'RealVisXL_V4.0.safetensors', 'Main SDXL', 'ACTIVE'],
            ['12', 'CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors', 'IPAdapter vision', 'SELECTED AWAY'],
            ['13', 'ip-adapter-plus_sdxl_vit-h.safetensors', 'IPAdapter', 'SELECTED AWAY'],
            ['21', 'diffusers_xl_depth_full.safetensors', 'Depth ControlNet', 'ACTIVE'],
            ['23', 'diffusers_xl_canny_full.safetensors', 'Canny ControlNet', 'ACTIVE'],
            ['38', 'depth_anything_v2_vitl.pth', 'Depth preprocessor', 'AVAILABLE · input2'],
            ['54', 'ae.safetensors', 'Main/PPL FLUX VAE', 'ACTIVE'],
            ['107', 'sam2.1_hiera_base_plus.safetensors · single_image', 'Prompted segmentation', 'ACTIVE'],
            ['112', 'gokaygokay/Florence-2-Flux-Large', 'Caption/detection', 'ACTIVE'],
            ['153', '4x-UltraSharp.pth', 'Upscale', 'BYPASSED UPSTREAM'],
            ['234', 'sam2.1_hiera_base_plus.safetensors · automaskgenerator', 'Auto segmentation', 'ACTIVE diagnostic'],
            ['466', 't5-v1_1-xxl-encoder-Q8_0.gguf + clip_l.safetensors', 'FLUX text encoders', 'ACTIVE'],
            ['467', 'flux1-dev-Q8_0.gguf', 'Main/PPL FLUX UNet', 'ACTIVE'],
          ],
        },
      },
      {
        id: 'custom-nodes',
        eyebrow: '02 · PACKAGE MAP',
        title: '18 external packages plus comfy-core',
        table: {
          columns: ['Package', 'Major node families'],
          rows: [
            ['ComfyUI-GGUF', '466, 467'],
            ['ComfyUI-segment-anything-2', '107, 114, 115, 232, 234, 584, 585'],
            ['ComfyUI_Comfyroll_CustomNodes', '168, 453, 459, 522, 535, 542, 552, 592, 630, 685, 695, 715, 732'],
            ['cg-image-filter', '779'],
            ['comfyui-custom-scripts', '158, 804, 832, 835, 841–846, 850'],
            ['comfyui-easy-use', '154, 420, 422, 565, 573, 702, 834'],
            ['comfyui-florence2', '112, 157, 550, 580'],
            ['comfyui-kjnodes', '456, 477, 541, 543, 693, 780–785'],
            ['ComfyUI-Logic', '600, 602, 607–609, 717, 720–723, 771, 887–893'],
            ['comfyui-post-processing-nodes', '751'],
            ['comfyui_controlnet_aux', '38'],
            ['comfyui_essentials', '146, 337, 840, 845'],
            ['comfyui_ipadapter_plus', '7, 9, 13'],
            ['ComfyUI_UltimateSDUpscale', '833'],
            ['efficiency-nodes-comfyui', '417–419, 848, 849'],
            ['masquerade-nodes-comfyui', '429, 449, 499–510, 747, 749, 754'],
            ['rgthree-comfy', '71, 72, 87, 141, 230, 231, 480, 518, 675'],
            ['was-node-suite-comfyui', '165, 293, 408, 475, 531, 591, 672, 684, 730'],
          ],
        },
      },
      {
        id: 'compatibility-limit',
        eyebrow: '03 · COMPATIBILITY',
        title: 'Serialized version не равна проверенной установке',
        facts: [
          { status: 'confirmed', title: 'Provider identity', text: 'Node properties сохраняют cnr_id и часто revision/version, использованные при сохранении workflow.' },
          { status: 'not-confirmed', title: 'Current installation', text: 'Учебник не подтверждает установленные revisions, Python, Torch, CUDA, frontend или model availability.' },
          { status: 'confirmed', title: 'Legacy warning', text: 'ComfyUI-Logic upstream архивирован и должен сопровождаться предупреждением о совместимости.' },
        ],
      },
    ],
  },
];
