import type { Chapter } from '../manual-types';

export const foundationChapters: Chapter[] = [
  {
    index: 0,
    slug: 'overview',
    navTitle: 'Master Architecture',
    eyebrow: 'FULL WORKFLOW',
    title: 'From BASE IMAGE to the active LQ output',
    lede:
      'The full graph combines SDXL, ControlNet, several mask systems, PEOPLE/PPL, main FLUX img2img, and saved post-processing branches. This page establishes the map used to read every other chapter.',
    status: 'confirmed',
    statusNote: '252 nodes · 341 links · 16 formal groups · 28 controls in the derived specification',
    visual: 'master',
    category: 'foundation',
    stage: 'architecture',
    relatedNodes: [79, 783, 1, 14, 565, 779, 459, 573, 67, 57, 53, 730, 833, 848, 849],
    relatedChapters: ['inputs', 'control-panel', 'sdxl', 'main-flux', 'output'],
    sections: [
      {
        id: 'production-path',
        eyebrow: '01 · ACTIVE DATA PLANE',
        title: 'The currently provable production path ends at node 730',
        paragraphs: [
          'BASE IMAGE 79 passes through shared resize 783. SDXL then uses checkpoint 2, conditioning 5/6, ControlNet stack 417→419→418, latent selector 535, KSampler 1, and decode 14.',
          'After the first detail transfer 565 and central fan-out 779, the image joins PEOPLE/PPL. The selected result 459 passes through detail transfer 573, VAE Encode 67, main FLUX sampler 57, decode 53, and active LQ save 730.',
        ],
        table: {
          columns: ['Stage', 'Nodes', 'Current role', 'State'],
          rows: [
            ['Input / resize', '79 → 783', 'BASE IMAGE and shared canvas', 'ACTIVE'],
            ['Main SDXL', '2 / 5 / 6 / 418 / 535 / 1 / 14', 'Create or transform the base scene', 'ACTIVE'],
            ['Detail bridge', '565 → 779', 'Preserve architectural detail and fan out', 'ACTIVE'],
            ['PEOPLE / PPL', '408…459', 'Generation, mask, preparation, composite, selection', 'ACTIVE · MODE 1'],
            ['Main FLUX', '573 → 67 → 57 → 53', 'Final img2img refinement', 'ACTIVE'],
            ['Current save', '53 → 730', 'LQ1 JPG output', 'ACTIVE'],
          ],
        },
      },
      {
        id: 'optional-tail',
        eyebrow: '02 · SAVED BUT BYPASSED',
        title: 'Upscale and Add Logo exist in the graph but are not executed by the current profile',
        paragraphs: [
          'The specification records 227 nodes in mode 0 and 25 nodes in mode 4. Those 25 nodes make up the Process UPSCALE and Process ADD LOGO groups.',
          'Save nodes 531 and 293 themselves remain in mode 0, but their upstream 833/848/849 is in mode 4. The accurate description is therefore upstream-bypassed, not save-node-bypassed.',
        ],
        facts: [
          { status: 'confirmed', title: 'HQ branch', text: '53 → 834 → 833 → 531 is preserved in topology; 834/833 are in mode 4.' },
          { status: 'confirmed', title: 'Overlay branch', text: '833 → 848 → 849 → 15/293 is preserved; processing nodes 840–851 are in mode 4.' },
          { status: 'not-confirmed', title: 'Runtime pixels', text: 'Workflow JSON does not prove that HQ, logo overlay, or final preview has ever executed in this configuration.' },
        ],
      },
      {
        id: 'current-profile',
        eyebrow: '03 · CURRENT PROFILE',
        title: 'Saved modes define the effective route',
        table: {
          columns: ['Control / node', 'Stored value', 'Effective meaning'],
          rows: [
            ['541', '1', 'TXT+CNET2IMG; empty latent 3; denoise 1.0'],
            ['168 / 721', '1 / 0', 'Plain SDXL; IPAdapter selected away and weight 0'],
            ['453', '1', 'GLOBAL FLUX conditioning 811'],
            ['543', '1', 'FLUX PEOPLE source for linked selectors'],
            ['565 / 573 / 720', 'add / 0.09', 'Two active detail-transfer stages'],
            ['834 / 833 / 848 / 849', 'mode 4', 'Post-FLUX upscale and overlays bypassed'],
          ],
        },
      },
      {
        id: 'evidence-limit',
        eyebrow: '04 · SOURCE LIMIT',
        title: 'Topology is confirmed by the derived specification, but the raw workflow is not included',
        facts: [
          { status: 'confirmed', title: 'Derived source', text: 'HANSEN_WORKFLOW_SPEC.json contains nodes, links, groups, controls, and the source-workflow SHA.' },
          { status: 'not-confirmed', title: 'Independent hash check', text: 'Epspoziciya_archviz_ph_sdxlflux_v001.json is absent from the published ZIP, so its SHA cannot be recalculated in this checkout.' },
          { status: 'not-confirmed', title: 'Visual result', text: 'A connected route does not prove quality, speed, or the presence of people in a particular render.' },
        ],
      },
    ],
  },
  {
    index: 0,
    slug: 'graph-reading',
    navTitle: 'How to Read the Graph',
    eyebrow: 'GRAPH LANGUAGE',
    title: 'Data plane, control plane, and effective runtime values',
    lede:
      'To read the Hansen graph accurately, separate signal type, stored widget value, linked input, selector state, and bypass mode.',
    status: 'confirmed',
    statusNote: 'Link types, slots, and node modes were extracted from HANSEN_WORKFLOW_SPEC.json',
    visual: 'graph-reading',
    category: 'foundation',
    stage: 'architecture',
    relatedNodes: [543, 715, 552, 535, 542, 592, 600, 630, 685, 695, 732],
    relatedChapters: ['control-panel', 'selector-logic', 'node-index'],
    sections: [
      {
        id: 'signal-types',
        eyebrow: '01 · SIGNAL TYPES',
        title: 'Link type tells you what is being passed between nodes',
        table: {
          columns: ['Type', 'Links', 'Practical meaning'],
          rows: [
            ['IMAGE', '126', 'Pixels / image batch'],
            ['INT', '55', 'Mode, size, steps, and linked selector value'],
            ['STRING', '26', 'Prompt fragments and text routing'],
            ['MASK', '23', 'Affected region for composite / inpaint / detail transfer'],
            ['CONDITIONING', '15', 'Encoded prompt conditioning'],
            ['MODEL', '13', 'Model object after loader or patch'],
            ['FLOAT', '11', 'Strength / denoise / weight'],
            ['LATENT', '10', 'Latent image before decode'],
          ],
        },
      },
      {
        id: 'widget-vs-link',
        eyebrow: '02 · PRECEDENCE',
        title: 'A linked input takes precedence over the text shown inside a selector',
        paragraphs: [
          'Node 715 stores widget value 2, but its Input socket is linked to node 543, whose current value is 1. The effective selection is therefore input 1.',
          'The same model applies to 459, 522, 535, 542, 552, 592, 630, 685, 695, and 732. During diagnostics, inspect the control link first and the widget second.',
        ],
        facts: [
          { status: 'confirmed', title: 'Node 715', text: '543 → Input of 715; stored 2 is not authoritative while the control link is connected.' },
          { status: 'inferred', title: 'Debug rule', text: 'When a UI label and the real route disagree, tracing should begin at the source control link.' },
        ],
      },
      {
        id: 'node-state',
        eyebrow: '03 · EXECUTION STATE',
        title: 'Active, selected away, and bypassed are different states',
        bullets: [
          'ACTIVE: node mode 0 and its input is selected by the current selector.',
          'SELECTED AWAY: node mode 0, but the downstream selector chooses another input.',
          'BYPASSED: node mode 4; the graph preserves the node and links, but processing is disabled.',
          'DIAGNOSTIC ONLY: preview/comparer receives data but does not form the final result.',
        ],
      },
    ],
  },
  {
    index: 0,
    slug: 'inputs',
    navTitle: 'Inputs & Data Contracts',
    eyebrow: 'INPUTS · RESIZE · BATCH',
    title: 'Files and dimensions entering the workflow',
    lede:
      'BASE IMAGE is required; depth, references, RGB mask, and overlays are used only by their corresponding branches. Several resize and original/resized switches operate between them.',
    status: 'confirmed',
    statusNote: 'Filenames and consumers are confirmed from serialized LoadImage nodes and topology',
    visual: 'inputs',
    category: 'foundation',
    stage: 'input',
    relatedNodes: [25, 41, 42, 79, 301, 309, 338, 693, 695, 685, 702, 780, 781, 782, 783, 784, 785, 827],
    relatedChapters: ['control-panel', 'controlnet', 'ipadapter-lora', 'positioning'],
    sections: [
      {
        id: 'input-files',
        eyebrow: '01 · FILE CONTRACTS',
        title: 'Seven LoadImage nodes serve different branches',
        table: {
          columns: ['Node', 'Stored filename', 'Role', 'Required when'],
          rows: [
            ['79', 'V_1_di.jpg', 'BASE IMAGE; image + optional mask', 'Always'],
            ['25', 'V_1_d.jpg', 'External depth source', '456 = 1 for Depth'],
            ['41', 'reference .jfif', 'Second IPAdapter reference', '168 = 2 and 630 = 2'],
            ['42', 'reference .jfif', 'First IPAdapter reference', '168 = 2'],
            ['338', 'V_1_g.jpg', 'RGB/CMY/B/W mask atlas', 'When color-coded masks are used'],
            ['301', 'logo.png', 'First overlay/logo', 'After Add Logo is enabled'],
            ['309', 'overlay image', 'Second overlay', 'After Add Logo is enabled'],
          ],
        },
      },
      {
        id: 'size-contracts',
        eyebrow: '02 · SIZE CONTRACTS',
        title: 'Several canvas sizes coexist in the graph',
        table: {
          columns: ['Stage', 'Node(s)', 'Stored / linked size', 'Cardinality'],
          rows: [
            ['Working base', '702 → 783', '1536 on the long side / shared W,H', 'image batch from input'],
            ['External maps', '784 / 785', '1920 × 1920, resize, divisible by 64', 'image'],
            ['PEOPLE latent', '827', '1312 × 1920', 'batch 1'],
            ['PEOPLE detection canvas', '780', '1920 × 1920', 'image + mask'],
            ['SDXL latent', '3', 'W,H linked from 783', 'batch 4'],
            ['Main FLUX model sampling', '64', 'W,H linked from 783', 'shared canvas'],
          ],
        },
      },
      {
        id: 'original-resized',
        eyebrow: '03 · ROUTING',
        title: 'Node 693 selects original or resized canvas for two downstream paths',
        paragraphs: [
          'Control 693 is linked to selectors 695 and 685. The first determines the source for general image switch 592; the second determines the canvas for alternative PPL return 459.',
          'Any positioning diagnosis should compare image, mask, and canvas dimensions at 780–785 rather than relying only on a visual preview.',
        ],
        facts: [
          { status: 'confirmed', title: 'Current value', text: '693 = 1, meaning RESIZE INPUT.' },
          { status: 'not-confirmed', title: 'File availability', text: 'A serialized filename does not prove that the file exists in the active ComfyUI input folder.' },
        ],
      },
    ],
  },
  {
    index: 0,
    slug: 'control-panel',
    navTitle: 'Controls & Mode Presets',
    eyebrow: 'CONTROL PLANE',
    title: '28 controls that change graph routing and parameters',
    lede:
      'The Hansen workflow controls generation mode, ControlNet sources, prompt routing, PEOPLE source, working resolution, and shared sampler settings through linked controls.',
    status: 'confirmed',
    statusNote: 'The complete control inventory was extracted from 16_ALL_CONTROLS_REFERENCE.csv and topology',
    visual: 'controls',
    category: 'foundation',
    stage: 'control',
    relatedNodes: [168, 453, 456, 459, 479, 522, 535, 541, 543, 552, 592, 600, 602, 607, 608, 609, 630, 685, 693, 695, 702, 715, 717, 720, 721, 722, 723, 771],
    relatedChapters: ['graph-reading', 'selector-logic', 'sdxl', 'controlnet', 'main-flux'],
    sections: [
      {
        id: 'all-controls',
        eyebrow: '01 · INVENTORY',
        title: 'All user-facing and linked controls',
        table: {
          columns: ['Node', 'Current', 'Purpose / options', 'Downstream'],
          rows: [
            ['168', '1', '1 SDXL / 2 SDXL+IPA', '87'],
            ['453', '1', '1 GLOBAL / 2 Florence2 conditioning', '62, 833'],
            ['456', '1', '1 input maps / 2 preprocessors', '542, 732'],
            ['459', '1 linked', 'FLUX or alternative PEOPLE composite', '480, 573'],
            ['479', '—', 'Fast Groups Bypasser; saved group toggles absent', 'UI only'],
            ['522', '1 linked', 'FLUX or alternative mask source', '508'],
            ['535', '1 linked', 'Empty / VAE-encoded SDXL latent', '1'],
            ['541', '1', '1 TXT+CNET2IMG / 2 IMG+CNET2IMG', '535, 592, 602'],
            ['543', '1', '1 PPL FLUX / 2 INPUT', '459, 522, 552, 715'],
            ['552', '1 linked', 'PEOPLE source for resize/inpaint', '503, 518, 780'],
            ['592', '1 linked', 'Selected main image', '585, 580, 536, 775, 565'],
            ['600', 'computed', 'Mode-dependent denoise output', '1'],
            ['602', 'a != b', 'Generation-mode comparison', '600'],
            ['607', '1.0', 'TXT mode denoise', '600'],
            ['608', '0.3', 'IMG mode denoise', '600'],
            ['609', '1', 'Comparison constant', '602'],
            ['630', '1 linked', '1 first / 2 both IPA references', '9'],
            ['685', '1 linked', 'Resized/original alternative composite', '459'],
            ['693', '1', '1 RESIZE / 2 ORIGINAL', '695, 685'],
            ['695', '1 linked', 'Resized/original base', '592'],
            ['702', '1536', 'Working resize target', '783 W/H'],
            ['715', '2 stored · 1 effective', 'Return / Downstream Selector', '552'],
            ['717', '0.44', 'Color from environment strength', '477'],
            ['720', '0.09', 'Stage 1 & 2 detail-transfer strength', '565, 573'],
            ['721', '0', 'IPAdapter weight', '7'],
            ['722', '0.31', 'Canny ControlNet strength', '419'],
            ['723', '0.36', 'Depth ControlNet strength', '417'],
            ['771', '24', 'Shared FLUX/PPL/inpaint/upscale steps', '59, 498, 819, 833'],
          ],
        },
      },
      {
        id: 'current-preset',
        eyebrow: '02 · CURRENT SAVED PROFILE',
        title: 'An active snapshot, not a universal recommendation',
        bullets: [
          '541=1: TXT+CNET2IMG, empty latent, denoise 1.0.',
          '456=1: input1 sources for Depth/Canny switches.',
          '168=1 and 721=0: plain SDXL; IPAdapter has no effect.',
          '453=1: GLOBAL FLUX prompt.',
          '543=1: PPL FLUX source.',
          '693=1: resized input.',
          'Upscale/Add Logo processing: mode 4.',
        ],
      },
      {
        id: 'safe-switching',
        eyebrow: '03 · MODE RECIPE',
        title: 'Change the source control, then verify every linked selector',
        paragraphs: [
          'To change modes safely, update the master control first, verify effective downstream values second, and inspect the first preview of the selected branch third. Visual presets in the manual should never be mistaken for live ComfyUI controls.',
        ],
        facts: [
          { status: 'inferred', title: 'Safe order', text: 'Source files/models → master control → linked selectors → first preview → final downstream.' },
          { status: 'not-confirmed', title: 'Fast Groups Bypasser toggles', text: 'Node 479 does not contain serialized per-group widget values; the exact UI state can only be reconstructed from node modes.' },
        ],
      },
    ],
  },
  {
    index: 0,
    slug: 'models-dependencies',
    navTitle: 'Models & Dependencies',
    eyebrow: 'LOADERS · CUSTOM NODES',
    title: 'Model manifest and package-to-node map',
    lede:
      'The workflow stores exact loader filenames and provider IDs, but does not prove that the files are present, that the same versions are currently installed, or that runtime compatibility has been verified.',
    status: 'confirmed',
    statusNote: 'Filenames and provider IDs are present in serialized nodes; runtime status is not confirmed',
    visual: 'models',
    category: 'foundation',
    stage: 'runtime',
    relatedNodes: [2, 12, 13, 21, 23, 54, 87, 107, 112, 153, 234, 466, 467],
    relatedChapters: ['resources', 'sdxl', 'controlnet', 'ipadapter-lora', 'main-flux'],
    sections: [
      {
        id: 'model-manifest',
        eyebrow: '01 · MODEL FILES',
        title: 'Loaders and their consumers',
        table: {
          columns: ['Loader', 'Filename / repo', 'Stage', 'Current use'],
          rows: [
            ['2', 'RealVisXL_V4.0.safetensors', 'Main SDXL', 'ACTIVE'],
            ['12', 'CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors', 'IPAdapter vision', 'SELECTED AWAY'],
            ['13', 'ip-adapter-plus_sdxl_vit-h.safetensors', 'IPAdapter', 'SELECTED AWAY'],
            ['21', 'diffusers_xl_depth_full.safetensors', 'Depth ControlNet', 'ACTIVE'],
            ['23', 'diffusers_xl_canny_full.safetensors', 'Canny ControlNet', 'ACTIVE'],
            ['38', 'depth_anything_v2_vitl.pth', 'Depth preprocessor', 'AVAILABLE · input2'],
            ['54', 'ae.safetensors', 'Main/PPL FLUX VAE', 'ACTIVE'],
            ['107', 'sam2.1_hiera_base_plus.safetensors · single_image', 'Prompted segmentation', 'ACTIVE'],
            ['112', 'gokaygokay/Florence-2-Flux-Large', 'Caption/detection', 'ACTIVE'],
            ['153', '4x-UltraSharp.pth', 'Upscale', 'BYPASSED UPSTREAM'],
            ['234', 'sam2.1_hiera_base_plus.safetensors · automaskgenerator', 'Auto segmentation', 'ACTIVE diagnostic'],
            ['466', 't5-v1_1-xxl-encoder-Q8_0.gguf + clip_l.safetensors', 'FLUX text encoders', 'ACTIVE'],
            ['467', 'flux1-dev-Q8_0.gguf', 'Main/PPL FLUX UNet', 'ACTIVE'],
          ],
        },
      },
      {
        id: 'custom-nodes',
        eyebrow: '02 · PACKAGE MAP',
        title: '18 external packages plus comfy-core',
        table: {
          columns: ['Package', 'Major node families'],
          rows: [
            ['ComfyUI-GGUF', '466, 467'],
            ['ComfyUI-segment-anything-2', '107, 114, 115, 232, 234, 584, 585'],
            ['ComfyUI_Comfyroll_CustomNodes', '168, 453, 459, 522, 535, 542, 552, 592, 630, 685, 695, 715, 732'],
            ['cg-image-filter', '779'],
            ['comfyui-custom-scripts', '158, 804, 832, 835, 841–846, 850'],
            ['comfyui-easy-use', '154, 420, 422, 565, 573, 702, 834'],
            ['comfyui-florence2', '112, 157, 550, 580'],
            ['comfyui-kjnodes', '456, 477, 541, 543, 693, 780–785'],
            ['ComfyUI-Logic', '600, 602, 607–609, 717, 720–723, 771, 887–893'],
            ['comfyui-post-processing-nodes', '751'],
            ['comfyui_controlnet_aux', '38'],
            ['comfyui_essentials', '146, 337, 840, 845'],
            ['comfyui_ipadapter_plus', '7, 9, 13'],
            ['ComfyUI_UltimateSDUpscale', '833'],
            ['efficiency-nodes-comfyui', '417–419, 848, 849'],
            ['masquerade-nodes-comfyui', '429, 449, 499–510, 747, 749, 754'],
            ['rgthree-comfy', '71, 72, 87, 141, 230, 231, 480, 518, 675'],
            ['was-node-suite-comfyui', '165, 293, 408, 475, 531, 591, 672, 684, 730'],
          ],
        },
      },
      {
        id: 'compatibility-limit',
        eyebrow: '03 · COMPATIBILITY',
        title: 'A serialized version is not the same as a verified installation',
        facts: [
          { status: 'confirmed', title: 'Provider identity', text: 'Node properties preserve cnr_id and often the revision/version used when the workflow was saved.' },
          { status: 'not-confirmed', title: 'Current installation', text: 'The manual does not confirm installed revisions, Python, Torch, CUDA, frontend, or model availability.' },
          { status: 'confirmed', title: 'Legacy warning', text: 'The ComfyUI-Logic upstream repository is archived and should carry a compatibility warning.' },
        ],
      },
    ],
  },
];
